param(
    [string]$SourceRoot = (Split-Path -Parent $PSScriptRoot),
    [string]$DestinationRoot = (Split-Path -Parent $PSScriptRoot)
)

$ErrorActionPreference = 'Stop'

function Read-GuideBlocks {
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "Guide source not found: $Path"
    }

    $text = [IO.File]::ReadAllText($Path)
    $matches = [regex]::Matches(
        $text,
        '(?ms)^RXPGuides\.RegisterGuide\(\[\[(.*?)^[ \t]*\]\]\)\s*'
    )
    $result = @{}
    foreach ($match in $matches) {
        $nameMatch = [regex]::Match($match.Groups[1].Value, '(?m)^#name\s+(.+?)\s*$')
        if (-not $nameMatch.Success) { continue }
        $name = $nameMatch.Groups[1].Value.Trim()
        if ($result.ContainsKey($name)) {
            throw "Duplicate guide '$name' in $Path"
        }
        $result[$name] = $match.Value.TrimEnd()
    }
    return $result
}

$setSource = Read-GuideBlocks (Join-Path $SourceRoot 'Guides\Classic-0.5.lua')
$keySource = Read-GuideBlocks (Join-Path $SourceRoot 'Guides\Classic-Attunements.lua')

$setNames = @(
    'Part 1: Bracers',
    'Part 2: Belt & Gloves',
    'Part 3: Pants, Shoulders & Boots',
    'Part 4: Helm & Chest'
)
$keyNames = @(
    'Molten Core Attunement',
    'Blackwing Lair Attunement',
    'Upper Blackrock Spire Key',
    'Scholomance Key (A)',
    'Scholomance Key (H)',
    'Blackrock Depths Key',
    'Dire Maul Key'
)

$blocks = New-Object 'System.Collections.Generic.List[string]'
$coordinateTravel = [ordered]@{
    '.subzone 2738 >>Travel to Southwind Village in |cFFfa9602Silithus|r' = '.goto Silithus,61.60,48.60,80 >>Travel to Southwind Village in |cFFfa9602Silithus|r'
    '.subzone 2256 >>Travel to Darkwhisper Gorge in |cFFfa9602Winterspring|r' = '.goto Winterspring,58.87,78.40,80 >>Travel to Darkwhisper Gorge in |cFFfa9602Winterspring|r'
    ".subzone 2744 >>Travel to Hive'Regal in |cFFfa9602Silithus|r" = ".goto Silithus,55.77,71.71,80 >>Travel to Hive'Regal in |cFFfa9602Silithus|r"
    '.subzone 2249 >>Travel to Frostwhisper Gorge in |cFFfa9602Winterspring|r' = '.goto Winterspring,61.44,68.26,80 >>Travel to Frostwhisper Gorge in |cFFfa9602Winterspring|r'
    ".subzone 2266 >>Travel to Tyr's Hand in |cFFfa9602Eastern Plaguelands|r" = ".goto Eastern Plaguelands,84.17,83.38,80 >>Travel to Tyr's Hand in |cFFfa9602Eastern Plaguelands|r"
    '.subzone 896 >>Travel to Purgation Isle in |cFFfa9602Hillsbrad Foothills|r' = '.goto Hillsbrad Foothills,19.67,76.92,80 >>Travel to Purgation Isle in |cFFfa9602Hillsbrad Foothills|r'
    '.subzone 2079 >>Travel to Alcaz Island in |cFFfa9602Dustwallow Marsh|r' = '.goto Dustwallow Marsh,76.91,18.24,80 >>Travel to Alcaz Island in |cFFfa9602Dustwallow Marsh|r'
    ".subzone 2158 >>Enter Emberstrife's Den" = ".goto Dustwallow Marsh,56.67,87.64,80 >>Enter Emberstrife's Den"
}
foreach ($name in @($setNames + $keyNames)) {
    $source = if ($setSource.ContainsKey($name)) { $setSource } else { $keySource }
    if (-not $source.ContainsKey($name)) {
        throw "Required endgame guide '$name' was not found"
    }
    $block = $source[$name]
    $block = [regex]::Replace($block, '(?m)^#classic\s*$', '<< ac335', 1)
    foreach ($route in $coordinateTravel.GetEnumerator()) {
        $block = $block.Replace($route.Key, $route.Value)
    }
    if ($block -notmatch '(?m)^<< ac335\s*$') {
        throw "Guide '$name' did not receive its 3.3.5 gate"
    }
    [void]$blocks.Add($block)
}

$unsupportedAreaPattern = '(?m)^\s*\.subzone\s+(?:896|2079|2158|2245|2249|2256|2266|2738|2744)\b'
if (($blocks -join "`n") -match $unsupportedAreaPattern) {
    throw 'A locale-sensitive endgame subzone was left without a coordinate travel gate.'
}

$header = @'
-- AUTO-GENERATED by tools/Build-ClassicEndgame335.ps1.
-- Curated from the bundled RestedXP legacy endgame guide sources.
-- Only chains verified for the AzerothCore 3.3.5 baseline are included.
-- Distributed under this repository's GPL-3.0 license; upstream attribution retained.

'@
$output = $header + ($blocks -join "`r`n`r`n") + "`r`n"
$destination = Join-Path $DestinationRoot 'Guides\Classic-Endgame335.lua'
$utf8NoBom = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($destination, $output, $utf8NoBom)

Write-Host "Generated Guides\Classic-Endgame335.lua with $($blocks.Count) verified guides."
